
export const PLANETS = [
  {
    id: "etheron",
    name: "ETHERON",
    image: "/images/etheron-big.png",
    galaxy: "Andromeda-IV",
    diameter: "16,400 km",
    dayLength: "26 Earth hours",
    avgTemp: "-20°C to 0°C",
    climate: "Polar",
    pos: { left: "50%", top: "78%" },
  },
  {
    id: "orionis",
    name: "ORIONIS",
    image: "/images/orionis-big.png",
    galaxy: "Virgo A",
    diameter: "120,780 km",
    dayLength: "4 Earth hours",
    avgTemp: "10°C to 40°C",
    climate: "Temperate",
    pos: { left: "24%", top: "76%" },
  },
  {
    id: "theronix",
    name: "THERONIX",
    image: "/images/theronix-big.png",
    galaxy: "Sombrero",
    diameter: "56,780 km",
    dayLength: "12 Earth hours",
    avgTemp: "60°C to 90°C",
    climate: "Tropical",
    pos: { left: "76%", top: "80%" },
  },
  {
    id: "lumenara",
    name: "LUMENARA",
    image: "/images/lumenara-big.png",
    galaxy: "Andromeda-IV",
    diameter: "11,540 km",
    dayLength: "56 Earth hours",
    avgTemp: "10°C to 30°C",
    climate: "Tropical",
    pos: { left: "14%", top: "86%" },
  },
];
